# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Run Trials

on:
  push:
    branches: [ "master", "dev", "Pierre", "Tom" ]
  pull_request:
    branches: [ "master", "dev", "Pierre", "Tom" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Clone TravisTrials
      run: git clone --branch=master https://github.com/Ludeme/TravisTrials.git ../TravisTrials
    - name: Build with Ant
      run: |
        cd PlayerDesktop
        ant clean test
